
package InterfaceGrafica;

import Implementacoes.FilaEnc;
import java.awt.Graphics;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/*
 * @author Gean RC
 */

public class Fila extends javax.swing.JFrame {
    
    public Fila(){
        initComponents();
        createBufferStrategy(1);
        setLocationRelativeTo(null);
    }

    FilaEnc fila = new FilaEnc();
    int y = 70;
    String v = new String();
    int c;
    int contador = 0;
    Graphics f; 
    
    public boolean validarCampos(){
        if(valor_txt.getText().isEmpty()){
            //Verifica se tem campo vazio
            JOptionPane.showMessageDialog(this, "Campo vazio! Por favor preencha!", "Campo vazio", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
                //verifica se foram colocados valores errados
            try {
                Integer.parseInt(valor_txt.getText());
            }catch (NumberFormatException e){
                //Exibe a mensagem de erro caso digitem errado
                JOptionPane.showMessageDialog(this, "Entrada invalida! Apenas numeros", "Invalido!", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        return true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inserir_bt = new javax.swing.JButton();
        remover_bt = new javax.swing.JButton();
        inicio_bt = new javax.swing.JButton();
        valor_txt = new javax.swing.JTextField();
        elementos_txt = new javax.swing.JLabel();
        inicio_ti = new javax.swing.JLabel();
        elementos_ti = new javax.swing.JLabel();
        inicio_txt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fila (Encadeada)");

        inserir_bt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        inserir_bt.setText("Inserir");
        inserir_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_btActionPerformed(evt);
            }
        });

        remover_bt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        remover_bt.setText("Remover");
        remover_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_btActionPerformed(evt);
            }
        });

        inicio_bt.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        inicio_bt.setText("Inicio");
        inicio_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_btActionPerformed(evt);
            }
        });

        valor_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valor_txt.setOpaque(false);
        valor_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_txtActionPerformed(evt);
            }
        });

        elementos_txt.setText(" ");

        inicio_ti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inicio_ti.setText("Inicio:");

        elementos_ti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        elementos_ti.setText("Elementos:");

        inicio_txt.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inicio_ti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inicio_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(remover_bt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inserir_bt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inicio_bt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(elementos_ti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(elementos_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valor_txt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicio_ti)
                    .addComponent(inicio_txt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementos_txt)
                    .addComponent(elementos_ti))
                .addGap(18, 18, 18)
                .addComponent(inserir_bt)
                .addGap(18, 18, 18)
                .addComponent(remover_bt)
                .addGap(18, 18, 18)
                .addComponent(inicio_bt)
                .addGap(18, 18, 18)
                .addComponent(valor_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserir_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_btActionPerformed
       if(validarCampos()){
            f = getBufferStrategy().getDrawGraphics();
            if(fila.vazia()){
                v = valor_txt.getText();
                c = Integer.parseInt(v);
                fila.insere(c);
                f.drawRect(150, y, 50, 35);
                f.drawLine(150,y+7 ,200 ,y+7);
                f.drawString(v, 160,y+9);
                f.dispose();            
                getBufferStrategy().show();
                y = y+50;
                valor_txt.setText(null);
                inicio_txt.setText(null);
                contador++;
                elementos_txt.setText(Integer.toString(contador));
            }
            else{
                v = valor_txt.getText();
                c = Integer.parseInt(v);
                fila.insere(c);
                f.drawRect(150, y, 50, 35);
                f.drawLine(150, y+7, 200, y+7);
                f.drawLine(175, y-30, 175, y);
                f.drawString(v, 160, y+9);
                f.dispose();
                getBufferStrategy().show();
                y = y+50;
                valor_txt.setText(null);
                inicio_txt.setText(null);
                contador++;
                elementos_txt.setText(Integer.toString(contador));
            }
        }
        valor_txt.setText("");
    }//GEN-LAST:event_inserir_btActionPerformed

    private void remover_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_btActionPerformed
       f = getBufferStrategy().getDrawGraphics();
        if(fila.vazia()){
            JOptionPane.showMessageDialog(rootPane, "Fila vazia", "ERRO", HEIGHT);
        }
        else {
            fila.remove();
            f.clearRect(150,(y-(contador*50)) , 55, 50);
            contador--;
            elementos_txt.setText(Integer.toString(contador));
        }
        inicio_txt.setText(null);
        valor_txt.setText("");
    }//GEN-LAST:event_remover_btActionPerformed
    private void inicio_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_btActionPerformed
        int v = fila.inicio(); 
        if(v>=0){
            int q = fila.inicio();
            String t = Integer.toString(q);
            inicio_txt.setText(t);            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Fila vazia", "ERRO", HEIGHT);
        }
    }//GEN-LAST:event_inicio_btActionPerformed

    private void valor_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windown".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elementos_ti;
    private javax.swing.JLabel elementos_txt;
    private javax.swing.JButton inicio_bt;
    private javax.swing.JLabel inicio_ti;
    private javax.swing.JLabel inicio_txt;
    private javax.swing.JButton inserir_bt;
    private javax.swing.JButton remover_bt;
    private javax.swing.JTextField valor_txt;
    // End of variables declaration//GEN-END:variables
}
